# Site
title:              kwon99
bio:                'Younghun Kwon'
description:        "kwon99"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                #//kwon198.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: kyonggi@kakao.com
blog:               kwon99
blog2:              https://kwon99.tistory.com
#twitter:           username
facebook:           100051172203191
github-url:         kwon99
#linkedin:          username
#xing:              username
instagram:          kwon99_blog
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              kwon9999
#dribbble:          username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
discord:            384205142825631746
youtube1:           UC0pND2u9Rf_gT75u8btIjZg
stackoverflow:      16866872/younghun-kwon
twitch:             kwon_99
lol:                1
# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
